// CoreMind（星枢智核）统一入口 —— 聚合门面，只 re-export，不写业务逻辑

export {
  type AgentConfig,
  type CoreMindConfig,
  type LoopActionConfig,
  type LoopConfig,
  type LoopVerificationConfig,
  loadConfigFile,
  type PermissionsConfig,
  parseAndValidate,
  parseConfigText,
  type QualityConfig,
  type RuntimeLimitsConfig,
  type TelemetryConfig,
  type TelemetryContentLevel,
  type TelemetryMode,
  type ToolEffectDeclaration,
  validateConfig,
  type WorkflowStep,
} from "coremind-config";
export {
  createErrorResponse,
  createEventNotification,
  createPythonToolCallNotification,
  createSuccessResponse,
  negotiateProtocolV2,
  PROTOCOL_V2_SCHEMA_BUNDLE,
  PROTOCOL_V2_SCHEMA_FINGERPRINT,
  PROTOCOL_V2_VERSION,
  PROTOCOL_VERSION,
  type ProtocolErrorResponse,
  type ProtocolEventNotification,
  type ProtocolRequest,
  type ProtocolRunSnapshot,
  type ProtocolSuccessResponse,
  type ProtocolV2ChatRequest,
  ProtocolV2ChatRequestSchema,
  type ProtocolV2ControlCommand,
  ProtocolV2ControlCommandSchema,
  type ProtocolV2ControlReceipt,
  ProtocolV2ControlReceiptSchema,
  type ProtocolV2ControlRequest,
  ProtocolV2ControlRequestSchema,
  ProtocolV2ErrorResponseSchema,
  type ProtocolV2EventEnvelope,
  ProtocolV2EventEnvelopeSchema,
  type ProtocolV2EventPage,
  ProtocolV2EventPageSchema,
  type ProtocolV2EventsRequest,
  ProtocolV2EventsRequestSchema,
  type ProtocolV2InitializeRequest,
  ProtocolV2InitializeRequestSchema,
  type ProtocolV2InitializeResult,
  ProtocolV2InitializeResultSchema,
  ProtocolV2NegotiationError,
  type ProtocolV2QueryRequest,
  ProtocolV2QueryRequestSchema,
  type ProtocolV2QueryResult,
  ProtocolV2QueryResultSchema,
  type ProtocolV2Request,
  ProtocolV2RequestSchema,
  type ProtocolV2ResumeRequest,
  ProtocolV2ResumeRequestSchema,
  type ProtocolV2RunHandle,
  ProtocolV2RunHandleSchema,
  type ProtocolV2RunRequest,
  ProtocolV2RunRequestSchema,
  type ProtocolV2StartRequest,
  ProtocolV2ValidationError,
  ProtocolValidationError,
  type ProtocolVersionRange,
  type PythonToolCallNotification,
  parseProtocolRequest,
  parseProtocolV2Request,
  parseRunSnapshot,
  RunSnapshotSchema,
} from "coremind-protocol";
export {
  type ApprovalDecision,
  buildAgentFromConfig,
  buildRepositoryMap,
  CHILD_RUN_LIMIT_DEFAULTS,
  ChatSession,
  type ChatTurnResult,
  type CheckpointDiff,
  CheckpointManager,
  type CheckpointRecord,
  type ChildRunBudgetAllocation,
  type ChildRunContextReference,
  type ChildRunContinuationGate,
  ChildRunCoordinator,
  type ChildRunCoordinatorHierarchyLimits,
  type ChildRunCoordinatorOptions,
  type ChildRunDelegationRequest,
  type ChildRunDispositionProjection,
  type ChildRunEnvironmentRequirement,
  type ChildRunExecutionAdapter,
  type ChildRunExecutionInput,
  type ChildRunFact,
  type ChildRunHandle,
  type ChildRunHierarchyLimits,
  type ChildRunJoinOptions,
  type ChildRunLifecyclePolicy,
  type ChildRunModelSnapshot,
  type ChildRunNodeProjection,
  type ChildRunPermissionSnapshot,
  type ChildRunPolicySnapshot,
  type ChildRunRecoveryAssessment,
  type ChildRunResult,
  type ChildRunTreeProjection,
  type ChildRunWorkspaceSnapshot,
  CODING_TOOL_CONTRACTS,
  type CodingEnvironmentChoice,
  type CodingEnvironmentSelection,
  CodingKernelError,
  type CodingKernelErrorCode,
  type CodingLanguage,
  type CodingRepositoryInspection,
  type CodingToolContract,
  type CodingToolId,
  type CommandGrader,
  type ControlApplyResult,
  type ControlReceipt,
  type ControlReceiptStatus,
  type CoreMindChildRunAdapter,
  type CoreMindChildRunAdapterOptions,
  CoreMindError,
  type CoreMindEvent,
  type CoreMindMessage,
  type CoreMindMessageContent,
  CoreMindRuntime,
  type CoreMindRuntimeOptions,
  type CoreMindToolContext,
  type CoreMindToolDefinition,
  type CoreMindToolOutput,
  type CoreMindTraceEvent,
  checkProject,
  childRunInputFingerprint,
  childRunRecoveryAssessment,
  childRunResultFingerprint,
  createCoreMindChildRunAdapter,
  createDenyPolicyExtension,
  createEngineeringKernelDefinition,
  createEngineeringTaskPlan,
  createProviderRequestReplayFact,
  createRunSnapshot,
  createTelemetryConfigurationFact,
  createTelemetryConsentFact,
  createTelemetryEgressAuthorization,
  createToolCallLifecycle,
  createTraceExporterExtension,
  type DelegationDispositionAction,
  type DelegationDispositionActor,
  type DelegationDispositionFact,
  type DelegationDispositionRequest,
  type DelegationRedelegationCancelledFact,
  type DiffGrader,
  DurableOperation,
  type DurableOperationSnapshot,
  defineExperiment,
  defineLifecycleExtension,
  defineTool,
  type EngineeringChange,
  type EngineeringControlEvent,
  type EngineeringDeliverySummary,
  EngineeringEvidenceLedger,
  type EngineeringPhaseId,
  type EngineeringTaskPlan,
  type EngineeringVerification,
  type EvaluationGrader,
  type EvaluationGraderResult,
  type EvaluationReport,
  type EvaluationSuite,
  type EvaluationSuiteResult,
  type ExperimentArm,
  type ExperimentDefinition,
  type ExperimentEnvironment,
  ExperimentError,
  type ExperimentRecord,
  type ExperimentRunEvidence,
  type ExperimentSelection,
  type FactAppendOptions,
  type FactDurabilityReceipt,
  FactLedger,
  type FactLedgerLevelMetrics,
  type FactLedgerMetrics,
  type FactLedgerStatus,
  type FileGrader,
  FileRunStore,
  fingerprintRunConfig,
  formatMetrics,
  inspectCheckpoint,
  inspectCodingRepository,
  inspectRuntimeCompatibility,
  isChildRunFact,
  isRunStateResumable,
  isTelemetryConsentFact,
  type JsonObjectSchema,
  type LanguageCandidate,
  LIFECYCLE_EVENTS,
  type LifecycleEventType,
  type LifecycleExtension,
  type LifecycleExtensionCapabilities,
  LifecycleExtensionError,
  type LifecycleExtensionEvent,
  LifecycleExtensionHost,
  type LifecycleExtensionPolicy,
  type LifecycleExtensionReceipt,
  type LocalObservabilityProjection,
  type LoopPhase,
  listInheritedProviders,
  listSupportedProviders,
  loadEvaluationSuite,
  MemoryRunStore,
  type OperationEvent,
  type OperationEventType,
  type OperationState,
  type OperationStateRecord,
  type OutcomeGrader,
  operationSnapshotFromRecords,
  type PackageManager,
  ProjectionEngine,
  type ProjectLocalObservabilityOptions,
  type ProtocolStartIdentity,
  type ProviderRequestReplayFact,
  type ProviderRequestReplayFixture,
  prepareRunResume,
  projectLocalObservability,
  projectToolCallLifecycles,
  type RecordedDelegationDisposition,
  type ReleaseReadiness,
  type ReplayFixture,
  ReplayKit,
  type ReplayResult,
  type RepositoryMap,
  type RepositoryMapEntry,
  type ResponseGrader,
  type RunControlCommand,
  type RunMetrics,
  type RunOutcome,
  type RunProjection,
  type RunResult,
  type RunResumePlan,
  type RunSnapshot,
  type RunSnapshotInput,
  RunStateJournal,
  type RunStateRecord,
  type RunStatus,
  type RunStore,
  type RunStoreDurability,
  type RunStoreDurabilityAcknowledgement,
  type RunStoreDurabilityBoundary,
  type RunStoreDurabilityMetrics,
  restoreCheckpoint,
  restoreDurableOperation,
  runEvaluationSuite,
  runExperiment,
  type SecretResolver,
  type StateGrader,
  type StepOutput,
  selectCodingEnvironment,
  selectExperimentArm,
  type TelemetryAuthorizationScope,
  type TelemetryConfigurationFact,
  type TelemetryConfigurationSource,
  type TelemetryConsentFact,
  type TelemetryConsentInput,
  type TelemetryDeliveryProjection,
  type TelemetryEgressAuthorization,
  TelemetryEgressController,
  type TelemetryEgressControllerOptions,
  type TelemetryExporter,
  TelemetryExporterError,
  type TelemetryExportRecord,
  type TelemetryFailureCode,
  type TelemetryPolicy,
  type ToolApprovalRequest,
  type ToolCallLifecycleFact,
  type ToolCallLifecycleState,
  type ToolCallResultAxes,
  type ToolEffect,
  ToolExecutionEngine,
  type TrajectoryGrader,
  type TrajectoryStep,
  telemetryConsentScopeFingerprint,
  telemetryFactPrefixFingerprint,
  validateTelemetryConfigurationFact,
  validateTelemetryConsentBinding,
  validateTelemetryConsentFact,
} from "coremind-runtime";
export {
  detectProjectLanguage,
  findSkill,
  findTemplate,
  type ProjectGuidanceOptions,
  type ProjectLanguage,
  resolveSkills,
  SKILLS,
  type SkillMeta,
  scaffoldProjectGuidance,
  TEMPLATES,
  type TemplateMeta,
} from "coremind-templates";
export {
  type BuildToolsOptions,
  buildTools,
  createUnifiedDiff,
  DiffLimitError,
  type DiffLimitErrorCode,
  diffFiles,
  type FileDiffOptions,
  GitAdapter,
  GitAdapterError,
  type GitAdapterErrorCode,
  type GitAdapterOptions,
  type GitDiffOptions,
  type GitLogOptions,
  type GitStatusEntry,
  ProcessRunner,
  ProcessRunnerError,
  type ProcessRunnerErrorCode,
  type ProcessRunRequest,
  type ProcessRunResult,
  type UnifiedDiffOptions,
} from "coremind-tools";
