// CoreMind（星枢智核）统一入口 —— 聚合门面，只 re-export，不写业务逻辑

export {
  type AgentConfig,
  type CoreMindConfig,
  loadConfigFile,
  type PermissionsConfig,
  parseAndValidate,
  parseConfigText,
  type QualityConfig,
  type RuntimeLimitsConfig,
  validateConfig,
  type WorkflowStep,
} from "coremind-config";
export {
  createErrorResponse,
  createEventNotification,
  createPythonToolCallNotification,
  createSuccessResponse,
  PROTOCOL_VERSION,
  type ProtocolErrorResponse,
  type ProtocolEventNotification,
  type ProtocolRequest,
  type ProtocolSuccessResponse,
  ProtocolValidationError,
  type PythonToolCallNotification,
  parseProtocolRequest,
} from "coremind-protocol";
export {
  type ApprovalDecision,
  buildAgentFromConfig,
  ChatSession,
  type ChatTurnResult,
  type CheckpointDiff,
  CheckpointManager,
  type CheckpointRecord,
  CoreMindError,
  type CoreMindEvent,
  CoreMindRuntime,
  type CoreMindRuntimeOptions,
  type CoreMindToolContext,
  type CoreMindToolDefinition,
  type CoreMindToolOutput,
  type CoreMindTraceEvent,
  checkProject,
  defineTool,
  type EvaluationReport,
  type EvaluationSuite,
  type EvaluationSuiteResult,
  FileRunStore,
  fingerprintRunConfig,
  formatMetrics,
  inspectCheckpoint,
  type JsonObjectSchema,
  listInheritedProviders,
  loadEvaluationSuite,
  MemoryRunStore,
  prepareRunResume,
  type ReleaseReadiness,
  type RunMetrics,
  type RunOutcome,
  type RunResult,
  type RunResumePlan,
  RunStateJournal,
  type RunStateRecord,
  type RunStore,
  restoreCheckpoint,
  runEvaluationSuite,
  type StepOutput,
  type ToolApprovalRequest,
} from "coremind-runtime";
export {
  detectProjectLanguage,
  findSkill,
  findTemplate,
  type ProjectGuidanceOptions,
  type ProjectLanguage,
  resolveSkills,
  SKILLS,
  type SkillMeta,
  scaffoldProjectGuidance,
  TEMPLATES,
  type TemplateMeta,
} from "coremind-templates";
export { type BuildToolsOptions, buildTools } from "coremind-tools";
