// CoreMind（星枢智核）统一入口 —— 聚合门面，只 re-export，不写业务逻辑

export {
  type AgentConfig,
  type CoreMindConfig,
  type LoopActionConfig,
  type LoopConfig,
  type LoopVerificationConfig,
  loadConfigFile,
  type PermissionsConfig,
  parseAndValidate,
  parseConfigText,
  type QualityConfig,
  type RuntimeLimitsConfig,
  type ToolEffectDeclaration,
  validateConfig,
  type WorkflowStep,
} from "coremind-config";
export {
  createErrorResponse,
  createEventNotification,
  createPythonToolCallNotification,
  createSuccessResponse,
  PROTOCOL_VERSION,
  type ProtocolErrorResponse,
  type ProtocolEventNotification,
  type ProtocolRequest,
  type ProtocolRunSnapshot,
  type ProtocolSuccessResponse,
  ProtocolValidationError,
  type PythonToolCallNotification,
  parseProtocolRequest,
  parseRunSnapshot,
  RunSnapshotSchema,
} from "coremind-protocol";
export {
  type ApprovalDecision,
  buildAgentFromConfig,
  buildRepositoryMap,
  ChatSession,
  type ChatTurnResult,
  type CheckpointDiff,
  CheckpointManager,
  type CheckpointRecord,
  CODING_TOOL_CONTRACTS,
  type CodingEnvironmentChoice,
  type CodingEnvironmentSelection,
  CodingKernelError,
  type CodingKernelErrorCode,
  type CodingLanguage,
  type CodingRepositoryInspection,
  type CodingToolContract,
  type CodingToolId,
  type CommandGrader,
  CoreMindError,
  type CoreMindEvent,
  type CoreMindMessage,
  type CoreMindMessageContent,
  CoreMindRuntime,
  type CoreMindRuntimeOptions,
  type CoreMindToolContext,
  type CoreMindToolDefinition,
  type CoreMindToolOutput,
  type CoreMindTraceEvent,
  checkProject,
  createDenyPolicyExtension,
  createEngineeringKernelDefinition,
  createEngineeringTaskPlan,
  createRunSnapshot,
  createTraceExporterExtension,
  type DiffGrader,
  DurableOperation,
  type DurableOperationSnapshot,
  defineExperiment,
  defineLifecycleExtension,
  defineTool,
  type EngineeringChange,
  type EngineeringControlEvent,
  type EngineeringDeliverySummary,
  EngineeringEvidenceLedger,
  type EngineeringPhaseId,
  type EngineeringTaskPlan,
  type EngineeringVerification,
  type EvaluationGrader,
  type EvaluationGraderResult,
  type EvaluationReport,
  type EvaluationSuite,
  type EvaluationSuiteResult,
  type ExperimentArm,
  type ExperimentDefinition,
  type ExperimentEnvironment,
  ExperimentError,
  type ExperimentRecord,
  type ExperimentRunEvidence,
  type ExperimentSelection,
  type FileGrader,
  FileRunStore,
  fingerprintRunConfig,
  formatMetrics,
  inspectCheckpoint,
  inspectCodingRepository,
  inspectRuntimeCompatibility,
  isRunStateResumable,
  type JsonObjectSchema,
  type LanguageCandidate,
  LIFECYCLE_EVENTS,
  type LifecycleEventType,
  type LifecycleExtension,
  type LifecycleExtensionCapabilities,
  LifecycleExtensionError,
  type LifecycleExtensionEvent,
  LifecycleExtensionHost,
  type LifecycleExtensionPolicy,
  type LifecycleExtensionReceipt,
  type LoopPhase,
  listInheritedProviders,
  listSupportedProviders,
  loadEvaluationSuite,
  MemoryRunStore,
  type OperationEvent,
  type OperationEventType,
  type OperationState,
  type OperationStateRecord,
  type OutcomeGrader,
  operationSnapshotFromRecords,
  type PackageManager,
  prepareRunResume,
  type ReleaseReadiness,
  type RepositoryMap,
  type RepositoryMapEntry,
  type ResponseGrader,
  type RunMetrics,
  type RunOutcome,
  type RunResult,
  type RunResumePlan,
  type RunSnapshot,
  type RunSnapshotInput,
  RunStateJournal,
  type RunStateRecord,
  type RunStatus,
  type RunStore,
  restoreCheckpoint,
  restoreDurableOperation,
  runEvaluationSuite,
  runExperiment,
  type StateGrader,
  type StepOutput,
  selectCodingEnvironment,
  selectExperimentArm,
  type ToolApprovalRequest,
  type ToolEffect,
  type TrajectoryGrader,
  type TrajectoryStep,
} from "coremind-runtime";
export {
  detectProjectLanguage,
  findSkill,
  findTemplate,
  type ProjectGuidanceOptions,
  type ProjectLanguage,
  resolveSkills,
  SKILLS,
  type SkillMeta,
  scaffoldProjectGuidance,
  TEMPLATES,
  type TemplateMeta,
} from "coremind-templates";
export {
  type BuildToolsOptions,
  buildTools,
  createUnifiedDiff,
  DiffLimitError,
  type DiffLimitErrorCode,
  diffFiles,
  type FileDiffOptions,
  GitAdapter,
  GitAdapterError,
  type GitAdapterErrorCode,
  type GitAdapterOptions,
  type GitDiffOptions,
  type GitLogOptions,
  type GitStatusEntry,
  ProcessRunner,
  ProcessRunnerError,
  type ProcessRunnerErrorCode,
  type ProcessRunRequest,
  type ProcessRunResult,
  type UnifiedDiffOptions,
} from "coremind-tools";
